[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "cita-vulnerabilities-collection"
authors = [{name = "Yieazy", email = "yuitta@163.com"}]
dynamic = ["version", "description"]
